#**********uniscope-driver-modify-file-on-qualcomm-platform*****************#
obj-y += b2c2/ saa7146/ 
obj-$(CONFIG_SMS_SDIO_DRV) += siano/
obj-$(CONFIG_VIDEO_CX2341X) += cx2341x.o
obj-$(CONFIG_VIDEO_BTCX)  += btcx-risc.o
obj-$(CONFIG_VIDEO_TVEEPROM) += tveeprom.o
obj-$(CONFIG_CYPRESS_FIRMWARE) += cypress_firmware.o
